language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: o+1yOoS7vsOFyvn5t89s7RAMglhLDjvcPF2935ToJTobp6JhO3Dugjw0EnisrzBa2lQBbsssOOVOJLGzVIEqgOeZRR3gns1VJkCNO+6y0ERbpJOExn1ajDktRMJ4v31hrjppv2QKt6r4iRnpRvvKS9B2izxsTaxdkqRZBO9BMu8=
  - secure: Z2/sCTq4w6AKqphZCOfMc7mrCDr6RXBex9vvk0mDR0kNGXx2bG1SbBNOK/zLtk0XCM3VN5LmaBguPt8nwCnlyfMUKQjKcr59umrl2LnD0TNbriV+zm6uA1tbHrNpqMNwTkQkuPzyI30k613Rr5tN+LtnDaC0qgmSr//Wl4uEWtM=
  - secure: pa/amolq1k8Sn7Mnu55Zvv6kPe5sr6aFrMLAQVdA7h6zKucf6q241+sWOPtUOJo5BPBZRG0M8XBJtZtlG7REmj7xZwnK3dr+2hTHAU0RLHbHsrvyY/KkLDo6AqAYE/nwR8Jscegv1iL0gtmaXk0ycLzp5AbttcgRW2P2xiCOcU8=
  - secure: ocA87V2coP+b6ftGeokb+oqWKBHN8X6xE0Rg8CQ3JjC2wZFaWKsVpklgguf3oJI5kT6rjue8rVmNNaVNMA2HhTXFjxEzEqSlEWYLSpcLozoSGFqLJO+OPoreeG163aaigXy62ZDilBp+3aIQtEtC/ShSa2Pbqu/dNs48+p2oqkA=
